version: '4'

services:
  django:
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    extra_hosts:
     - "host.docker.internal:host-gateway"


